services:
  dns:
    build: .
    container_name: dns
    user: root
    network_mode: host
    # ports:
    #   - "53:53/udp"
    #   - "53:53/tcp"
    volumes:
      - ./logs:/var/named/logs
      - ./zones:/var/named/zones
      - ./dns.d/named.conf:/etc/named.conf
    cap_add:
      - NET_ADMIN
    privileged: true
